jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('TOYS_BIGQUERY_PROJECT') }}"
      dataset: toys
      threads: 24
      keyfile_json:
        type: service_account
        project_id: "{{ env_var('TOYS_BIGQUERY_PROJECT') }}"
        private_key_id: "{{ env_var('TOYS_GCP_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('TOYS_GCP_PRIVATE_KEY') }}"
        client_email: "{{ env_var('TOYS_GCP_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('TOYS_GCP_CLIENT_ID') }}"
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: "{{ env_var('TOYS_GCP_CLIENT_CERT_URL') }}"