[sources]
dagster-buildkite = { path = ".buildkite/dagster-buildkite", editable = true }
dagit = { path = "python_modules/dagit/", editable = true }
dagster = { path = "python_modules/dagster/", editable = true }
dagster-webserver = { path = "python_modules/dagster-webserver/", editable = true }
dagster-pipes = { path = "python_modules/dagster-pipes/", editable = true }
dagster-graphql = { path = "python_modules/dagster-graphql/", editable = true }
dagster-test = { path = "python_modules/dagster-test/", editable = true }
automation = { path = "python_modules/automation/", editable = true }
dagster-airbyte = { path = "python_modules/libraries/dagster-airbyte/", editable = true }
dagster-aws = { path = "python_modules/libraries/dagster-aws/", editable = true }
dagster-azure = { path = "python_modules/libraries/dagster-azure/", editable = true }
dagster-celery = { path = "python_modules/libraries/dagster-celery/", editable = true }
dagster-celery-docker = { path = "python_modules/libraries/dagster-celery-docker/", editable = true }
dagster-celery-k8s = { path = "python_modules/libraries/dagster-celery-k8s/", editable = true }
dagster-census = { path = "python_modules/libraries/dagster-census/", editable = true }
dagster-dask = { path = "python_modules/libraries/dagster-dask/", editable = true }
dagster-databricks = { path = "python_modules/libraries/dagster-databricks/", editable = true }
dagster-datadog = { path = "python_modules/libraries/dagster-datadog/", editable = true }
dagster-datahub = { path = "python_modules/libraries/dagster-datahub/", editable = true }
dagster-dbt = { path = "python_modules/libraries/dagster-dbt/", editable = true }
dagster-deltalake = { path = "python_modules/libraries/dagster-deltalake/", editable = true }
dagster-deltalake-pandas = { path = "python_modules/libraries/dagster-deltalake-pandas/", editable = true }
dagster-deltalake-polars = { path = "python_modules/libraries/dagster-deltalake-polars/", editable = true }
dagster-docker = { path = "python_modules/libraries/dagster-docker/", editable = true }
dagster-duckdb = { path = "python_modules/libraries/dagster-duckdb/", editable = true }
dagster-duckdb-pandas = { path = "python_modules/libraries/dagster-duckdb-pandas/", editable = true }
dagster-duckdb-polars = { path = "python_modules/libraries/dagster-duckdb-polars/", editable = true }
dagster-duckdb-pyspark = { path = "python_modules/libraries/dagster-duckdb-pyspark/", editable = true }
dagster-embedded-elt = { path = "python_modules/libraries/dagster-embedded-elt/", editable = true }
dagster-fivetran = { path = "python_modules/libraries/dagster-fivetran/", editable = true }
dagster-gcp = { path = "python_modules/libraries/dagster-gcp/", editable = true }
dagster-gcp-pandas = { path = "python_modules/libraries/dagster-gcp-pandas/", editable = true }
dagster-gcp-pyspark = { path = "python_modules/libraries/dagster-gcp-pyspark/", editable = true }
dagster-ge = { path = "python_modules/libraries/dagster-ge/", editable = true }
dagster-github = { path = "python_modules/libraries/dagster-github/", editable = true }
dagster-k8s = { path = "python_modules/libraries/dagster-k8s/", editable = true }
dagster-looker = { path = "python_modules/libraries/dagster-looker/", editable = true }
dagster-managed-elements = { path = "python_modules/libraries/dagster-managed-elements/", editable = true }
dagster-mlflow = { path = "python_modules/libraries/dagster-mlflow/", editable = true }
dagster-msteams = { path = "python_modules/libraries/dagster-msteams/", editable = true }
dagster-mysql = { path = "python_modules/libraries/dagster-mysql/", editable = true }
dagster-openai = { path = "python_modules/libraries/dagster-openai/", editable = true }
dagster-pagerduty = { path = "python_modules/libraries/dagster-pagerduty/", editable = true }
dagster-pandas = { path = "python_modules/libraries/dagster-pandas/", editable = true }
dagster-pandera = { path = "python_modules/libraries/dagster-pandera/", editable = true }
dagster-papertrail = { path = "python_modules/libraries/dagster-papertrail/", editable = true }
dagster-polars = { path = "python_modules/libraries/dagster-polars/", editable = true }
dagster-postgres = { path = "python_modules/libraries/dagster-postgres/", editable = true }
dagster-powerbi = { path = "python_modules/libraries/dagster-powerbi/", editable = true }
dagster-prometheus = { path = "python_modules/libraries/dagster-prometheus/", editable = true }
dagster-pyspark = { path = "python_modules/libraries/dagster-pyspark/", editable = true }
dagster-sdf = { path = "python_modules/libraries/dagster-sdf/", editable = true }
dagster-shell = { path = "python_modules/libraries/dagster-shell/", editable = true }
dagster-sigma = { path = "python_modules/libraries/dagster-sigma/", editable = true }
dagster-slack = { path = "python_modules/libraries/dagster-slack/", editable = true }
dagster-snowflake = { path = "python_modules/libraries/dagster-snowflake/", editable = true }
dagster-snowflake-pandas = { path = "python_modules/libraries/dagster-snowflake-pandas/", editable = true }
dagster-snowflake-pyspark = { path = "python_modules/libraries/dagster-snowflake-pyspark/", editable = true }
dagster-spark = { path = "python_modules/libraries/dagster-spark/", editable = true }
dagster-ssh = { path = "python_modules/libraries/dagster-ssh/", editable = true }
dagster-tableau = { path = "python_modules/libraries/dagster-tableau/", editable = true }
dagster-twilio = { path = "python_modules/libraries/dagster-twilio/", editable = true }
dagster-wandb = { path = "python_modules/libraries/dagster-wandb/", editable = true }
dagstermill = { path = "python_modules/libraries/dagstermill/", editable = true }
